Scheduler-App/Models/Domain/Program.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Scheduler_App.Models.Domain
{
    public class Program
    {
        public int Id { get; set; }
        [RegularExpression("^[a-zA-Z ]+$", ErrorMessage = "Please Enter Only Alphabets in ProgramName Field")]
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public virtual List<Course> Courses { get; set; }

        public Program()
        {   
            Courses = new List<Course>();
        }
    }
}

Scheduler-App/Controllers/ProgramController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using FluentDateTime;
using Scheduler_App.Models;
using Scheduler_App.Models.Domain;
using Scheduler_App.Models.Enum;
using Scheduler_App.Models.ViewModel;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Scheduler_App.Controllers
{
    public class ProgramController : Controller
    {
        private ApplicationDbContext DbContext;
        public ProgramController()
        {
            DbContext = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            var model = DbContext
                .ProgramDatabase
                .ProjectTo<CreateEditSchoolProgramViewModel>()
                .ToList();
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = nameof(UserRoles.Admin))]
        public ActionResult CreateProgram()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = nameof(UserRoles.Admin))]
        public ActionResult CreateProgram(CreateEditSchoolProgramViewModel formData)
        {
            return SaveProgram(null, formData);
        }

        private ActionResult SaveProgram(int? id, CreateEditSchoolProgramViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (DbContext.ProgramDatabase.Any(p =>
            p.Name == formData.Name &&
            (!id.HasValue || p.Id != id.Value)))
            {
                ModelState.AddModelError(nameof(CreateEditSchoolProgramViewModel.Name),
                    "Program Name Should Be Unique");
                return View();
            }

            var program = Mapper.Map<Program>(formData);
            if (!id.HasValue)
            {
                DbContext.ProgramDatabase.Add(program);
                DbContext.SaveChanges();
                return RedirectToAction("Details", new { id = program.Id });
            }

            else
            {
                program = DbContext.ProgramDatabase.FirstOrDefault(p => p.Id == id);
                if (program == null)
                {
                    return RedirectToAction(nameof(ProgramController.Index));
                }
            }

            program.Name = formData.Name;
            program.StartDate = formData.StartDate;
            var firstCourse = program.Courses.First();
            var startDate = firstCourse.StartDate;
            firstCourse.StartDate = formData.StartDate;
            var lastCourse = program.Courses.Last();
            if(lastCourse != null)
            {
                foreach(var course in program.Courses)
                {
                    if (firstCourse == null)
                    {
                        course.StartDate = course.Program.StartDate;
                        var totalDays = Convert.ToInt32(course.Hours / course.DailyHours);
                        course.EndDate = course.StartDate.AddBusinessDays(totalDays - 1);             
                        var startTime = course.StartTime = course.StartDate.TimeOfDay;
                        var remainingHours = course.Hours - (course.DailyHours * (totalDays));
                        var hours = remainingHours + startTime.Hours;
                        var remainingTime = TimeSpan.FromHours(hours);
                        remainingTime = remainingTime.Add(TimeSpan.FromMinutes(startTime.Minutes));
                        course.EndTime = remainingTime;
                    }
                    else
                    {
                        var totalDays = Convert.ToInt32(course.Hours / course.DailyHours);
                        course.EndDate = lastCourse.EndDate.AddBusinessDays(totalDays - 1);
                        course.StartDate = Convert.ToDateTime(lastCourse.EndDate);
                        var startTime = course.StartTime = course.StartDate.TimeOfDay;
                        var remainingHours = course.Hours - (course.DailyHours * (totalDays));
                        var hours = remainingHours + startTime.Hours;
                        var remainingTime = TimeSpan.FromHours(hours);
                        remainingTime = remainingTime.Add(TimeSpan.FromMinutes(startTime.Minutes));
                        course.EndTime = remainingTime;
                    }
                }
            }

            DbContext.SaveChanges();

            return RedirectToAction("Details", new { id = program.Id });
        }

        [HttpGet]
        [Authorize(Roles = nameof(UserRoles.Admin))]
        public ActionResult EditProgram(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(nameof(ProgramController.Index));
            }
            var program = DbContext.ProgramDatabase.FirstOrDefault(p => p.Id == id);
            if (program == null)
            {
                return RedirectToAction(nameof(ProgramController.Index));
            }

            var model = new CreateEditSchoolProgramViewModel();
            model.Name = program.Name;
            model.StartDate = program.StartDate;
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = nameof(UserRoles.Admin))]
        public ActionResult EditProgram(int id, CreateEditSchoolProgramViewModel formData)
        {
            return SaveProgram(id, formData);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(ProgramController.Index));
            }
            var program = DbContext.ProgramDatabase.Find(id);
            if (program == null)
            {
                return RedirectToAction(nameof(ProgramController.Index));
            }
            return View(program);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var program = DbContext.ProgramDatabase.Find(id);
            var course = DbContext.CourseDatabase.Where(p => p.ProgramId == id).ToList();
            foreach (var singleCourse in course)
            {
                DbContext.CourseDatabase.Remove(singleCourse);
            }

            DbContext.ProgramDatabase.Remove(program);
            DbContext.SaveChanges();

            TempData["Message"] = "You Successfully deleted the Program.";

            return RedirectToAction(nameof(ProgramController.Index));
        }

        [HttpGet]
        public ActionResult ProgramCourse()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ProgramCourse(int? id, CreateEditCourseViewModel formData, int? programId)
        {
            if (!ModelState.IsValid)
            {
                return View(formData);
            }

            var course = Mapper.Map<Course>(formData);
            if (!id.HasValue)
            {
                if (course != null)
                {
                    var program = DbContext.ProgramDatabase.FirstOrDefault(p => p.Id == programId);
                    var firstCourse = program.Courses.ElementAtOrDefault(0);
                    if (firstCourse == null)
                    {
                        course.StartDate = program.StartDate;
                        var totalDays = Convert.ToInt32(course.Hours / course.DailyHours);
                        course.EndDate = course.StartDate.AddBusinessDays(totalDays - 1);
                        var startTime = course.StartTime = course.StartDate.TimeOfDay;
                        var remainingHours = course.Hours - (course.DailyHours * (totalDays));
                        var hours = remainingHours + startTime.Hours;
                        var remainingTime = TimeSpan.FromHours(hours);
                        remainingTime = remainingTime.Add(TimeSpan.FromMinutes(startTime.Minutes));
                        course.EndTime = remainingTime;                     
                    }
                    else
                    {
                        var lastCourse = program.Courses.Last();
                        var totalDays = Convert.ToInt32(course.Hours / course.DailyHours);
                        course.EndDate = lastCourse.EndDate.AddBusinessDays(totalDays - 1);
                        course.StartDate = Convert.ToDateTime(lastCourse.EndDate);
                        var startTime = course.StartTime = course.StartDate.TimeOfDay;
                        var remainingHours = course.Hours - (course.DailyHours * (totalDays - 1));
                        var hours = remainingHours + startTime.Hours;
                        var remainingTime = TimeSpan.FromHours(hours);
                        remainingTime = remainingTime.Add(TimeSpan.FromMinutes(startTime.Minutes));
                        course.EndTime = remainingTime;
                    }
                }

                DbContext.CourseDatabase.Add(course);
                DbContext.SaveChanges();
            }
            else
            {
                course = DbContext.CourseDatabase.FirstOrDefault(p => p.Id == id);
                if (course == null)
                {
                    return RedirectToAction(nameof(ProgramController.Index));
                }
            }

            course.Name = formData.Name;
            course.Hours = formData.Hours;

            DbContext.SaveChanges();

            return RedirectToAction(nameof(ProgramController.Details), new { id = programId });
        }

        [HttpPost]
        public ActionResult DeleteProgramCourse(int id, int Courseid)
        {
            Program program = DbContext.ProgramDatabase.Find(id);
            var course = DbContext.CourseDatabase.FirstOrDefault(p => p.Id == Courseid);
            var courseId = course.Id;
            Courseid = courseId;

            DbContext.CourseDatabase.Remove(course);
            DbContext.SaveChanges();

Scheduler-App/Views/Program/CreateProgram.cshtml
@model CreateEditSchoolProgramViewModel

@{
    ViewBag.Title = "Create Program";
}
<div class="body-content" style="margin-bottom:360px">
    <div class="card card-stats mb-4 mb-xl-0 shadow--hover">
        <div class="card-header">
            <h2>Create School Program</h2>
        </div>
        <div class="card-body" style="width:400px">
            @Html.ValidationSummary(false, "", new { @class = "text-danger small" })

            @using (Html.BeginForm("CreateProgram", "Program", FormMethod.Post,
                new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.Name, "School Program Name", new { @class = "form-control-label", })
                    <div class="input-group input-group-alternative">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-book"></i></span>
                        </div>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = nameof(Model.Name), style = "padding-left:5px;" })
                    </div>
                </div>

                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.StartDate, "Start Date", new { @class = "form-control-label" })
                    <div class="input-group input-group-alternative">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                        </div>
                        @Html.TextBoxFor(model => model.StartDate, new { @type = "datetime-local", placeholder = nameof(Model.StartDate) })
                    </div>
                </div>

                <div class="form-inline row">
                    <div class="text-center col">
                        <button type="submit" class="btn btn-success my-4">Create School Program</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Scheduler-App/Views/Program/Delete.cshtml
@model  Program

@{
    ViewBag.Title = "Delete";
}
<div class="body-content" style="margin-bottom:360px">
    <div class="card card-stats mb-4 mb-xl-0 shadow--hover">
        <div class="card-header">
            <h2>Are you sure you want to delete this Program?</h2>
        </div>
        <div class="card-body" style="width:500px">
            <h4>Program</h4>
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.StartDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StartDate)
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    <div style="margin-top:10px; ">
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Scheduler-App/Views/Program/Details.cshtml
@model SchoolProgramViewModel
@{
    ViewBag.Title = "Details";
}

<div class="body-content" style="margin-bottom:480px; width:600px">
    <div class="card card-stats mb-4 mb-xl-0 shadow--hover">
        <div class="card-header">
            <h2>Details</h2>
        </div>

        <table class="table table-condensed no-border" id="sample-datatables">
            <thead>
                <tr>
                    <th>Program Name</th>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <th>Program Start Date</th>
                    <td>@Model.StartDate</td>
                </tr>
                <tr>
                    <th style="display:flex; justify-content:flex-start">
                        List Of Courses
                        (
                        <div style="display:flex; justify-content:space-around">
                            <a href="@Url.Action("ProgramCourse", "Program", new { programId = ViewBag.id})">Create Course</a>
                        </div>
                        )
                    </th>
                    <td>
                        @foreach (var record in Model.Courses)
                        {
                            <div style="display:flex; justify-content:flex-start">
                                <p>
                                    <a href="@Url.Action("Details", "Course", new { id = record.Id} )">
                                        @record.Name
                                    </a>
                                </p>
                                <form method="post" action="@Url.Action("DeleteProgramCourse","Program", new {id = ViewBag.id, Courseid = record.Id })">
                                    <button class="btn-delete" style="margin-left:10px; margin-top:-5px; color:red; background:none; border:none; height:30px;font-size:small">Delete</button>
                                </form>
                            </div>
                        }
                    </td>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
        <div style="margin-left:12px; font-size:medium ">
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

Scheduler-App/Views/Program/EditProgram.cshtml
@model CreateEditSchoolProgramViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="body-content" style="margin-bottom:360px">
    <div class="card card-stats mb-4 mb-xl-0 shadow--hover">
        <div class="card-header">
            <h2>Edit School Program</h2>
        </div>
        <div class="card-body" style="width:400px">

            @Html.ValidationSummary(false, "", new { @class = "text-danger small" })

            @using (Html.BeginForm("EditProgram", "Program", FormMethod.Post,
                new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.Name, "School Program Name", new { @class = "form-control-label", })
                    <div class="input-group input-group-alternative">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-book"></i></span>
                        </div>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = nameof(Model.Name), style = "padding-left:5px;" })
                    </div>
                </div>
                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.StartDate, "Start Date", new { @class = "form-control-label" })
                    <div class="input-group input-group-alternative">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                        </div>
                        @Html.EditorFor(model => model.StartDate, new { @type = "datetime-local", placeholder = nameof(Model.StartDate) })
                    </div>
                </div>

                <div class="form-inline row">
                    <div class="text-center col">
                        <button type="submit" class="btn btn-success my-4">Update</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Scheduler-App/Views/Program/Index.cshtml
@model List<CreateEditSchoolProgramViewModel>

@{
    ViewBag.Title = "View Programs";
}

@section css {
    <link rel="stylesheet"
          href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
}

@section Scripts {
    <script type="text/javascript"
            src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sample-datatables').DataTable();
        });
    </script>
}


<h2>List of Programs</h2>

@Html.ValidationSummary(false)
<h5>
    <strong>
        @Html.ActionLink("Create New", "CreateProgram")
    </strong>
</h5>

@if (!Model.Any())
{
    <div style="margin-bottom:600px">
        <p><strong>No Program Available</strong></p>
    </div>
}
else
{
    if (TempData["Message"] != null)
    {
        <div class="alert alert-danger">@TempData["Message"]</div>
    }
    <table id="sample-datatables" class="table table-striped" style="margin-bottom:400px">
        <thead>
            <tr>
                <th>Program</th>
                <th>Start Date</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var program in Model)
            {
            <tr>
                <td>
                    <a href="@Url.Action("Details", "Program", new { id = program.Id} )">
                        @program.Name
                    </a>
                </td>
                <td>
                @program.StartDate.ToShortDateString()</td>

                <td>
                    @if (User.IsInRole("Admin"))
                    {
                        <a href="@Url.Action("EditProgram", "Program", new { id = program.Id })">
                            <i title="Edit Program" class="fas fa-pencil-square-o"></i>
                        </a>
                    }
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = program.Id })
                </td>
            </tr>
            }
        </tbody>
    </table>

}

Scheduler-App/Views/Program/ProgramCourse.cshtml
@model CreateEditCourseViewModel

@{
    ViewBag.Title = "Create ProgramCourse";
}

<div class="body-content" style="margin-bottom:360px">
    <div class="card card-stats mb-4 mb-xl-0 shadow--hover">
        <div class="card-header">
            <h2>Create Course</h2>
        </div>
        <div class="card-body" style="width: 400px">
            <form method="post">
                @Html.ValidationSummary(false, "", new { @class = "text-danger small" })
                @Html.AntiForgeryToken()
                <div class="form-group mb-3">
                    @Html.LabelFor(model => model.Name, "Course Name", new { @class = "form-control-label" })
                    <div class="input-group input-group-alternative">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="ni ni-caps-small"></i></span>
                        </div>
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = nameof(Model.Name), style = "padding-left:5px;" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Hours, "Course Time", new { @class = "form-control-label" })
                    <div class="input-group input-group-alternative">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="ni ni-watch-time"></i></span>
                        </div>
                        <input type="number" min="0" name="@nameof(Model.Hours)" value="Hours" class="form-control" placeholder="Course Hours" />
                    </div>
                </div>
                <div class="form-inline row">
                    <div class="text-center col">
                        <button type="submit" class="btn btn-success my-4">Create Course</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>